### ISSUE TITLE
Add manage schedule tool

### ISSUE THREAD

**Issue by viroulep** [viroulep/wc2017#1]
- For the competitors to see their groups
- For the competition manager to schedule "Activities" (as per the [WCIF](https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#heading=h.a8wx47sshf0x))

@jfly expressed his interest with helping building a tool to create and manage a competition schedule (reason is thewca/worldcubeassociation.org#278).

So I'd like to keep the "manage schedule" part as independent as possible from any other stuff in the app, so that we can integrate it to the WCA website when done (and if it's satisfying :p).

I think this schedule manager should provide several features:
- Provide a calendar view on a range of date. Even a few hours, use case for this is that you have a calendar displaying the "3x3 first round", and when you click on it you land on the "groups" calendar for the 3x3 first round.
- The calendar should be able to display any event (as in "something that happens during the day", *not* as in "3x3") that provides a starting and ending date.
- Ideally for competition managers it should provide drag and drop across the displayed date range.
- We should be able to add a specific event to it.
- If the event is a WCA event, we should be able to display information attached to it (cutoff, time limit, qualification time, number to proceed, [...]).

I quickly look through available options and existing stuff:
 - cubecomp.de has a basic schedule display (relevant code [here](https://github.com/fw42/cubecomp/blob/8c68868a1f62de82af3a0275fe55340af939e324/app/views/liquid/_schedule.html.erb), and [here](https://github.com/fw42/cubecomp/blob/master/app/controllers/admin/events_controller.rb)). We can definitely take ideas from there, but I don't think it's totally fitting our needs.
- a few gems exist for displaying a calendar, but most of them are inactive and/or outdated. I found [simple_calendar](https://github.com/excid3/simple_calendar), which is still active and has a very promising description!

**Comment by jfly** [comment]
> Ideally for competition managers it should provide drag and drop across the displayed date range.

The way we got this working for CCM was to use the very awesome [fullcalendar.io](https://fullcalendar.io/) with a special plugin [we wrote](https://github.com/jfly/ccm/blob/master/client/vendor/z_CustomWeekView.js).

> I found simple_calendar, which is still active and has a very promising description!

I haven't looked into it too much yet, but I imagine adding drag drop would be a pain, just because it's a pure ruby thing?

**Comment by viroulep** [comment]
I very quickly took a look at fullcalendar.io, and it seems perfect.
We just need a controller which can respond to json with the events we want to display!
I've started to play around with it, and I'll continue with [this post](https://web.archive.org/web/20160531044930/http://blog.crowdint.com/2014/02/18/fancy-calendars-for-your-web-application-with-fullcalendar.html).
Hopefully I'll get around with a basic working setup quickly :)

**Comment by jfly** [comment]
Sweet! CC-ing @jonatanklosko here, who has experiemented with JSON API stuff, and might have opinions on jbuilder vs other tools out there.

Also, as you know, you could add webpack support to your rails app and use yarn to install fullcalendar instead of https://github.com/bokmann/fullcalendar-rails. You already know it's a little bit of a pain for developers, but it's really nice to be using modern javascript over on the WCA website.

**Comment by jonatanklosko** [comment]
[ActiveRecordsSerializers](https://github.com/rails-api/active_model_serializers) seems to be a nice lib, especially when relations come in. I think it depends on the actual purpose and building a JSON response like a view may be handy as well.

**Comment by viroulep** [comment]
That's definitely a powerful extension!

Beyond the week/day scale, you can also scale the time slot to have fine-grain event such as 10 minutes groups:
![schedule-test](https://cloud.githubusercontent.com/assets/1007485/26033214/c5992364-38a7-11e7-9024-473abcc83424.png)

There is also a built-in "list" view:
![schedule-list-test](https://cloud.githubusercontent.com/assets/1007485/26033233/3726551a-38a8-11e7-8993-58c9c2eef387.png)

Which pretty much solves the "personal schedule" issue on its own!
